import Head from 'next/head'
import Image from 'next/image'
// components
import Story from '../components/homepageComponents/Story'
import HeroSection from '../components/homepageComponents/HeroSection'
import Promotion from '../components/homepageComponents/Promotion'
import Courses from '../components/Courses'
import Testimonials from '../components/homepageComponents/Testimonials'
import Contact from '../components/homepageComponents/Contact'
import Membership from '../components/homepageComponents/Membership'
import Activities from '../components/homepageComponents/Activities'

export default function Home() {
  return (
    <div className='w-screen ' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <Story />
      <Activities />
      <Promotion />
      <Courses />
      <Testimonials />
      <Contact />
      <Membership />
    </div>
  )
}
